--[[
	© CloudSixteen.com do not share, re-distribute or modify
	without permission of its author (kurozael@gmail.com).
--]]

table.insert(Clockwork.voices.chatClasses, "request");
table.insert(Clockwork.voices.chatClasses, "radio");
table.insert(Clockwork.voices.chatClasses, "dispatch");

Clockwork.voices:RegisterGroup("Dispatch", false, function(player)
	local faction = player:GetFaction();

	return faction == FACTION_SCANNER;
end);

Clockwork.voices:RegisterGroup("Combine", false, function(player)
	local faction = player:GetFaction();

	return Schema:PlayerIsCombine(player) and faction != FACTION_SCANNER;
end);

Clockwork.voices:RegisterGroup("Vortigaunt", false, function(player)
	return player:GetFaction() == FACTION_VORTIGAUNT;
end);

Clockwork.voices:Add("Dispatch", "Anti-Citizen", "Attention ground units. Anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav");
Clockwork.voices:Add("Dispatch", "Anti-Civil", "Protection team alert. Evidence of anti-civil activity in this community. Code: ASSEMBLE, PLAN, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav");
Clockwork.voices:Add("Dispatch", "Person Interest", "Attention please. Unidentified person of interest confirm your civil status with local protection team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav");
Clockwork.voices:Add("Dispatch", "Citizen Inaction", "Citizen reminder. Inaction is conspiracy. Report counter behaviour to a Civil Protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav");
Clockwork.voices:Add("Dispatch", "Unrest Structure", "Alert community ground protection units, local unrest structure detected. ASSEMBLE, ADMINISTER, PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav");
Clockwork.voices:Add("Dispatch", "Status Evasion", "Attention protection team. Status evasion in progress in this community. RESPOND, ISOLATE, ENQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav");
Clockwork.voices:Add("Dispatch", "Lockdown", "Attention all ground protection teams. Judgment waiver now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav");
Clockwork.voices:Add("Dispatch", "Rations Deducted", "Attention occupants. Your block is now charged with permissive inactive cohesion. Five ration units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav");
Clockwork.voices:Add("Dispatch", "Inspection", "Citizen notice. Priority identification check in progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav");
Clockwork.voices:Add("Dispatch", "Inspection 2", "Attention please. All citizens in local residential block, assume your inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav");
Clockwork.voices:Add("Dispatch", "Miscount Detected", "Attention resident. Miscount detected in your block. Co-operation with your Civil Protection team permit full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav");
Clockwork.voices:Add("Dispatch", "Infection", "Attention resident. This block contains potential civil infection. INFORM, CO-OPERATE, ASSEMBLE.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav");
Clockwork.voices:Add("Dispatch", "Relocation", "Citizen notice. Failure to co-operate will result in permanent off-world relocation.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav");
Clockwork.voices:Add("Dispatch", "Unrest Code", "Attention community. Unrest procedure code is now in effect. INOCULATE, SHIELD, PACIFY. Code: PRESSURE, SWORD, STERILIZE.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav");
Clockwork.voices:Add("Dispatch", "Evasion", "Attention please. Evasion behaviour consistent with mal-compliant defendant. Ground protection team, alert. Code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav");
Clockwork.voices:Add("Dispatch", "Individual", "Individual. You are charged with social endangerment, level one. Protection unit, prosecution code: DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav");
Clockwork.voices:Add("Dispatch", "Autonomous", "Attention all ground protection teams. Autonomous judgement is now in effect, sentencing is now discretionary. Code: AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav");
Clockwork.voices:Add("Dispatch", "Citizenship", "Individual. You are convicted of multi anti-civil violations. Implicit citizenship revoked. Status: MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav");
Clockwork.voices:Add("Dispatch", "Malcompliance", "Individual. You are charged with capital malcompliance, anti-citizen status approved.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav");
Clockwork.voices:Add("Dispatch", "Exogen", "Overwatch acknowledges critical exogen breach, AirWatch augmentation force dispatched and inbound. Hold for reinforcements.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav");
Clockwork.voices:Add("Dispatch", "Failure", "Attention ground units. Mission failure will result in permanent off-world assignment. Code reminder: SACRIFICE, COAGULATE, PLAN.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav");

Clockwork.voices:Add("Combine", "Sweeping", "Sweeping for suspect.", "npc/metropolice/hiding02.wav");
Clockwork.voices:Add("Combine", "Isolate", "Isolate!", "npc/metropolice/hiding05.wav");
Clockwork.voices:Add("Combine", "You Can Go", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav");
Clockwork.voices:Add("Combine", "Need Assistance", "Eleven-ninety-nine, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav");
Clockwork.voices:Add("Combine", "Administer", "Administer.", "npc/metropolice/vo/administer.wav");
Clockwork.voices:Add("Combine", "Affirmative", "Affirmative.", "npc/metropolice/vo/affirmative.wav");
Clockwork.voices:Add("Combine", "All Units Move In", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav");
Clockwork.voices:Add("Combine", "Amputate", "Amputate.", "npc/metropolice/vo/amputate.wav");
Clockwork.voices:Add("Combine", "Anti-Citizen", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav");
Clockwork.voices:Add("Combine", "Citizen", "Citizen.", "npc/metropolice/vo/citizen.wav");
Clockwork.voices:Add("Combine", "Copy", "Copy.", "npc/metropolice/vo/copy.wav");
Clockwork.voices:Add("Combine", "Cover Me", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav");
Clockwork.voices:Add("Combine", "Assist Trespass", "Assist for a criminal trespass!", "npc/metropolice/vo/criminaltrespass63.wav");
Clockwork.voices:Add("Combine", "Destroy Cover", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav");
Clockwork.voices:Add("Combine", "Don't Move", "Don't move!", "npc/metropolice/vo/dontmove.wav");
Clockwork.voices:Add("Combine", "Final Verdict", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav");
Clockwork.voices:Add("Combine", "Final Warning", "Final warning!", "npc/metropolice/vo/finalwarning.wav");
Clockwork.voices:Add("Combine", "First Warning", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav");
Clockwork.voices:Add("Combine", "Get Down", "Get down!", "npc/metropolice/vo/getdown.wav");
Clockwork.voices:Add("Combine", "Get Out", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav");
Clockwork.voices:Add("Combine", "Suspect One", "I got suspect one here.", "npc/metropolice/vo/gotsuspect1here.wav");
Clockwork.voices:Add("Combine", "Help", "Help!", "npc/metropolice/vo/help.wav");
Clockwork.voices:Add("Combine", "Running", "He's running!", "npc/metropolice/vo/hesrunning.wav");
Clockwork.voices:Add("Combine", "Hold It", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav");
Clockwork.voices:Add("Combine", "Move Along Repeat", "I said move along.", "npc/metropolice/vo/isaidmovealong.wav");
Clockwork.voices:Add("Combine", "Malcompliance", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav");
Clockwork.voices:Add("Combine", "Keep Moving", "Keep moving!", "npc/metropolice/vo/keepmoving.wav");
Clockwork.voices:Add("Combine", "Lock Position", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav");
Clockwork.voices:Add("Combine", "Trouble", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav");
Clockwork.voices:Add("Combine", "Look Out", "Look out!", "npc/metropolice/vo/lookout.wav");
Clockwork.voices:Add("Combine", "Minor Hits", "Minor hits, continuing prosecution.", "npc/metropolice/vo/minorhitscontinuing.wav");
Clockwork.voices:Add("Combine", "Move", "Move!", "npc/metropolice/vo/move.wav");
Clockwork.voices:Add("Combine", "Move Along", "Move along!", "npc/metropolice/vo/movealong3.wav");
Clockwork.voices:Add("Combine", "Move Back", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav");
Clockwork.voices:Add("Combine", "Move It", "Move it!", "npc/metropolice/vo/moveit2.wav");
Clockwork.voices:Add("Combine", "Hardpoint", "Moving to hardpoint.", "npc/metropolice/vo/movingtohardpoint.wav");
Clockwork.voices:Add("Combine", "Officer Help", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav");
Clockwork.voices:Add("Combine", "Privacy", "Possible level three civil privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav");
Clockwork.voices:Add("Combine", "Judgement", "Suspect prepare to receive civil judgement!", "npc/metropolice/vo/prepareforjudgement.wav");
Clockwork.voices:Add("Combine", "Priority Two", "I have a priority two anti-citizen here!", "npc/metropolice/vo/priority2anticitizenhere.wav");
Clockwork.voices:Add("Combine", "Prosecute", "Prosecute!", "npc/metropolice/vo/prosecute.wav");
Clockwork.voices:Add("Combine", "Amputate Ready", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav");
Clockwork.voices:Add("Combine", "Rodger That", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav");
Clockwork.voices:Add("Combine", "Search", "Search!", "npc/metropolice/vo/search.wav");
Clockwork.voices:Add("Combine", "Shit", "Shit!", "npc/metropolice/vo/shit.wav");
Clockwork.voices:Add("Combine", "Sentence Delivered", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav");
Clockwork.voices:Add("Combine", "Sterilize", "Sterilize!", "npc/metropolice/vo/sterilize.wav");
Clockwork.voices:Add("Combine", "Take Cover", "Take cover!", "npc/metropolice/vo/takecover.wav");
Clockwork.voices:Add("Combine", "Restrict", "Restrict!", "npc/metropolice/vo/restrict.wav");
Clockwork.voices:Add("Combine", "Restricted", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav");
Clockwork.voices:Add("Combine", "Second Warning", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav");
Clockwork.voices:Add("Combine", "Verdict", "You want a non-compliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav");
Clockwork.voices:Add("Combine", "Backup", "Backup!", "npc/metropolice/vo/backup.wav");
Clockwork.voices:Add("Combine", "Apply", "Apply.", "npc/metropolice/vo/apply.wav");
Clockwork.voices:Add("Combine", "Restriction", "Terminal restriction zone.", "npc/metropolice/vo/terminalrestrictionzone.wav");
Clockwork.voices:Add("Combine", "Complete", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav");
Clockwork.voices:Add("Combine", "Location Unknown", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav");
Clockwork.voices:Add("Combine", "Can 1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav");
Clockwork.voices:Add("Combine", "Can 2", "Pick... up... the can.", "npc/metropolice/vo/pickupthecan2.wav");
Clockwork.voices:Add("Combine", "Wrap It", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav");
Clockwork.voices:Add("Combine", "Can 3", "I said pickup the can!", "npc/metropolice/vo/pickupthecan3.wav");
Clockwork.voices:Add("Combine", "Can 4", "Now, put it in the trash can.", "npc/metropolice/vo/putitinthetrash1.wav");
Clockwork.voices:Add("Combine", "Can 5", "I said put it in the trash can!", "npc/metropolice/vo/putitinthetrash2.wav");
Clockwork.voices:Add("Combine", "Now Get Out", "Now get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav");
Clockwork.voices:Add("Combine", "Haha", "Haha.", "npc/metropolice/vo/chuckle.wav");
Clockwork.voices:Add("Combine", "X-Ray", "X-Ray!", "npc/metropolice/vo/xray.wav");
Clockwork.voices:Add("Combine", "Patrol", "Patrol!", "npc/metropolice/vo/patrol.wav");
Clockwork.voices:Add("Combine", "Serve", "Serve.", "npc/metropolice/vo/serve.wav");
Clockwork.voices:Add("Combine", "Knocked Over", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav");
Clockwork.voices:Add("Combine", "Watch It", "Watch it!", "npc/metropolice/vo/watchit.wav");
Clockwork.voices:Add("Combine", "Restricted Canals", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav");
Clockwork.voices:Add("Combine", "505", "Subject is five-oh-five!", "npc/metropolice/vo/subjectis505.wav");
Clockwork.voices:Add("Combine", "404", "Possible four-zero-oh here!", "npc/metropolice/vo/possible404here.wav");
Clockwork.voices:Add("Combine", "Vacate", "Vacate citizen!", "npc/metropolice/vo/vacatecitizen.wav");
Clockwork.voices:Add("Combine", "Escapee", "Priority two escapee.", "npc/combine_soldier/vo/prioritytwoescapee.wav");
Clockwork.voices:Add("Combine", "Objective", "Priority one objective.", "npc/combine_soldier/vo/priority1objective.wav");
Clockwork.voices:Add("Combine", "Payback", "Payback.", "npc/combine_soldier/vo/payback.wav");
Clockwork.voices:Add("Combine", "Got Him Now", "Affirmative, we got him now.", "npc/combine_soldier/vo/affirmativewegothimnow.wav");
Clockwork.voices:Add("Combine", "Antiseptic", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav");
Clockwork.voices:Add("Combine", "Cleaned", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav");
Clockwork.voices:Add("Combine", "Engaged Cleanup", "Engaged in cleanup.", "npc/combine_soldier/vo/engagedincleanup.wav");
Clockwork.voices:Add("Combine", "Engaging", "Engaging.", "npc/combine_soldier/vo/engaging.wav");
Clockwork.voices:Add("Combine", "Full Response", "Executing full response.", "npc/combine_soldier/vo/executingfullresponse.wav");
Clockwork.voices:Add("Combine", "Heavy Resistance", "Overwatch advise, we have heavy resistance.", "npc/combine_soldier/vo/heavyresistance.wav");
Clockwork.voices:Add("Combine", "Inbound", "Inbound.", "npc/combine_soldier/vo/inbound.wav");
Clockwork.voices:Add("Combine", "Lost Contact", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav");
Clockwork.voices:Add("Combine", "Move In", "Move in!", "npc/combine_soldier/vo/movein.wav");
Clockwork.voices:Add("Combine", "Harden Position", "Harden that position!", "npc/combine_soldier/vo/hardenthatposition.wav");
Clockwork.voices:Add("Combine", "Go Sharp", "Go sharp, go sharp!", "npc/combine_soldier/vo/gosharpgosharp.wav");
Clockwork.voices:Add("Combine", "Delivered", "Delivered.", "npc/combine_soldier/vo/delivered.wav");
Clockwork.voices:Add("Combine", "Necrotics Inbound", "Necrotics, inbound!", "npc/combine_soldier/vo/necroticsinbound.wav");
Clockwork.voices:Add("Combine", "Necrotics", "Necrotics.", "npc/combine_soldier/vo/necrotics.wav");
Clockwork.voices:Add("Combine", "Outbreak", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav");
Clockwork.voices:Add("Combine", "Copy That", "Copy that.", "npc/combine_soldier/vo/copythat.wav");
Clockwork.voices:Add("Combine", "Outbreak Status", "Outbreak status is code.", "npc/combine_soldier/vo/outbreakstatusiscode.wav");
Clockwork.voices:Add("Combine", "Overwatch", "Overwatch!", "npc/combine_soldier/vo/overwatch.wav");
Clockwork.voices:Add("Combine", "Preserve", "Preserve!", "npc/metropolice/vo/preserve.wav");
Clockwork.voices:Add("Combine", "Pressure", "Pressure!", "npc/metropolice/vo/pressure.wav");
Clockwork.voices:Add("Combine", "Phantom", "Phantom!", "npc/combine_soldier/vo/phantom.wav");
Clockwork.voices:Add("Combine", "Stinger", "Stinger!", "npc/combine_soldier/vo/stinger.wav");
Clockwork.voices:Add("Combine", "Shadow", "Shadow!", "npc/combine_soldier/vo/shadow.wav");
Clockwork.voices:Add("Combine", "Savage", "Savage!", "npc/combine_soldier/vo/savage.wav");
Clockwork.voices:Add("Combine", "Reaper", "Reaper!", "npc/combine_soldier/vo/reaper.wav");
Clockwork.voices:Add("Combine", "Victor", "Victor!", "npc/metropolice/vo/victor.wav");
Clockwork.voices:Add("Combine", "Sector", "Sector!", "npc/metropolice/vo/sector.wav");
Clockwork.voices:Add("Combine", "Inject", "Inject!", "npc/metropolice/vo/inject.wav");
Clockwork.voices:Add("Combine", "Dagger", "Dagger!", "npc/combine_soldier/vo/dagger.wav");
Clockwork.voices:Add("Combine", "Blade", "Blade!", "npc/combine_soldier/vo/blade.wav");
Clockwork.voices:Add("Combine", "Razor", "Razor!", "npc/combine_soldier/vo/razor.wav");
Clockwork.voices:Add("Combine", "Nomad", "Nomad!", "npc/combine_soldier/vo/nomad.wav");
Clockwork.voices:Add("Combine", "Judge", "Judge!", "npc/combine_soldier/vo/judge.wav");
Clockwork.voices:Add("Combine", "Ghost", "Ghost!", "npc/combine_soldier/vo/ghost.wav");
Clockwork.voices:Add("Combine", "Sword", "Sword!", "npc/combine_soldier/vo/sword.wav");
Clockwork.voices:Add("Combine", "Union", "Union!", "npc/metropolice/vo/union.wav");
Clockwork.voices:Add("Combine", "Helix", "Helix!", "npc/combine_soldier/vo/helix.wav");
Clockwork.voices:Add("Combine", "Storm", "Storm!", "npc/combine_soldier/vo/storm.wav");
Clockwork.voices:Add("Combine", "Spear", "Spear!", "npc/combine_soldier/vo/spear.wav");
Clockwork.voices:Add("Combine", "Vamp", "Vamp!", "npc/combine_soldier/vo/vamp.wav");
Clockwork.voices:Add("Combine", "Nova", "Nova!", "npc/combine_soldier/vo/nova.wav");
Clockwork.voices:Add("Combine", "Mace", "Mace!", "npc/combine_soldier/vo/mace.wav");
Clockwork.voices:Add("Combine", "Grid", "Grid!", "npc/combine_soldier/vo/grid.wav");
Clockwork.voices:Add("Combine", "Kilo", "Kilo!", "npc/combine_soldier/vo/kilo.wav");
Clockwork.voices:Add("Combine", "Echo", "Echo!", "npc/combine_soldier/vo/echo.wav");
Clockwork.voices:Add("Combine", "Dash", "Dash!", "npc/combine_soldier/vo/dash.wav");
Clockwork.voices:Add("Combine", "Apex", "Apex!", "npc/combine_soldier/vo/apex.wav");
Clockwork.voices:Add("Combine", "Jury", "Jury!", "npc/metropolice/vo/jury.wav");
Clockwork.voices:Add("Combine", "King", "King!", "npc/metropolice/vo/king.wav");
Clockwork.voices:Add("Combine", "Lock", "Lock!", "npc/metropolice/vo/lock.wav");
Clockwork.voices:Add("Combine", "Vice", "Vice!", "npc/metropolice/vo/vice.wav");
Clockwork.voices:Add("Combine", "Zero", "Zero!", "npc/metropolice/vo/zero.wav");
Clockwork.voices:Add("Combine", "Zone", "Zone!", "npc/metropolice/vo/zone.wav");

Clockwork.voices:Add("Vortigaunt", "Accept Charge", "Accept the charge.", "vo/npc/vortigaunt/acceptcharge.wav");
Clockwork.voices:Add("Vortigaunt", "Accompany", "Gladly we accompany.", "vo/npc/vortigaunt/accompany.wav");
Clockwork.voices:Add("Vortigaunt", "Affirmed", "Affirmed.", "vo/npc/vortigaunt/affirmed.wav");
Clockwork.voices:Add("Vortigaunt", "All For Now", "That is all for now.", "vo/npc/vortigaunt/allfornow.wav");
Clockwork.voices:Add("Vortigaunt", "Allow Me", "Allow me.", "vo/npc/vortigaunt/allowme.wav");
Clockwork.voices:Add("Vortigaunt", "As You Wish", "As you wish.", "vo/npc/vortigaunt/asyouwish.wav");
Clockwork.voices:Add("Vortigaunt", "Believe The Opposite", "We believe the opposite.", "vo/npc/vortigaunt/vanswer03.wav");
Clockwork.voices:Add("Vortigaunt", "By Our Honor", "By our honor.", "vo/npc/vortigaunt/ourhonor.wav");
Clockwork.voices:Add("Vortigaunt", "Calm", "Caaaalm yourself.", "vo/npc/vortigaunt/calm.wav");
Clockwork.voices:Add("Vortigaunt", "Caution", "Caution!", "vo/npc/vortigaunt/caution.wav");
Clockwork.voices:Add("Vortigaunt", "Certainly", "Certainly.", "vo/npc/vortigaunt/certainly.wav");
Clockwork.voices:Add("Vortigaunt", "Concern", "Your concern is touching.", "vo/npc/vortigaunt/vanswer07.wav");
Clockwork.voices:Add("Vortigaunt", "Delay", "Is there reason for delay?", "vo/npc/vortigaunt/reasondelay.wav");
Clockwork.voices:Add("Vortigaunt", "Done", "Done.", "vo/npc/vortigaunt/done.wav");
Clockwork.voices:Add("Vortigaunt", "Dreamed", "We have dreamed of this moment.", "vo/npc/vortigaunt/dreamed.wav");
Clockwork.voices:Add("Vortigaunt", "Empower Us", "Empower us!", "vo/npc/vortigaunt/empowerus.wav");
Clockwork.voices:Add("Vortigaunt", "Expected", "We expected this much.", "vo/npc/vortigaunt/vanswer05.wav");
Clockwork.voices:Add("Vortigaunt", "Failed You", "We fear we have failed you.", "vo/npc/vortigaunt/fearfailed.wav");
Clockwork.voices:Add("Vortigaunt", "For Freedom", "For freedom!", "vo/npc/vortigaunt/forfreedom.wav");
Clockwork.voices:Add("Vortigaunt", "Forward", "Forward!", "vo/npc/vortigaunt/forward.wav");
Clockwork.voices:Add("Vortigaunt", "Gladly", "Gladly.", "vo/npc/vortigaunt/gladly.wav");
Clockwork.voices:Add("Vortigaunt", "Halt", "Halt.", "vo/npc/vortigaunt/halt.wav");
Clockwork.voices:Add("Vortigaunt", "Here", "Here.", "vo/npc/vortigaunt/here.wav");
Clockwork.voices:Add("Vortigaunt", "Hold", "Hold.", "vo/npc/vortigaunt/hold.wav");
Clockwork.voices:Add("Vortigaunt", "Hold Still", "Hold still.", "vo/npc/vortigaunt/holdstill.wav");
Clockwork.voices:Add("Vortigaunt", "Hope", "Hope is in sight.", "vo/npc/vortigaunt/vques03.wav");
Clockwork.voices:Add("Vortigaunt", "Hopeless", "Our cause seems hopeless.", "vo/npc/vortigaunt/hopeless.wav");
Clockwork.voices:Add("Vortigaunt", "Honor", "It is an honor.", "vo/npc/vortigaunt/honor.wav");
Clockwork.voices:Add("Vortigaunt", "Honored", "We are honored.", "vo/npc/vortigaunt/wehonored.wav");
Clockwork.voices:Add("Vortigaunt", "Honor Is Ours", "The honor is ours.", "vo/npc/vortigaunt/honourours.wav");
Clockwork.voices:Add("Vortigaunt", "Illusions", "You are not the first to harbor such illusions.", "vo/npc/vortigaunt/vanswer02.wav");
Clockwork.voices:Add("Vortigaunt", "Know You", "We know you.", "vo/npc/vortigaunt/weknowyou.wav");
Clockwork.voices:Add("Vortigaunt", "Lead On", "Lead on.", "vo/npc/vortigaunt/leadon.wav");
Clockwork.voices:Add("Vortigaunt", "Lead Us", "Lead us.", "vo/npc/vortigaunt/leadus.wav");
Clockwork.voices:Add("Vortigaunt", "Live To Serve", "We live to serve.", "vo/npc/vortigaunt/livetoserve.wav");
Clockwork.voices:Add("Vortigaunt", "Lost All Dear", "We have lost all dear to us.", "vo/npc/vortigaunt/alldear.wav");
Clockwork.voices:Add("Vortigaunt", "Mutual", "Our purpose is mutual.", "vo/npc/vortigaunt/mutual.wav");
Clockwork.voices:Add("Vortigaunt", "Mutual Feeling", "The feeling is mutual.", "vo/npc/vortigaunt/vanswer16.wav");
Clockwork.voices:Add("Vortigaunt", "Mystery", "We serve the same mystery.", "vo/npc/vortigaunt/mystery.wav");
Clockwork.voices:Add("Vortigaunt", "Onward", "Onward!", "vo/npc/vortigaunt/onward.wav");
Clockwork.voices:Add("Vortigaunt", "Opaque", "Your mind is opaque.", "vo/npc/vortigaunt/opaque.wav");
Clockwork.voices:Add("Vortigaunt", "Our Place", "Our place is here.", "vo/npc/vortigaunt/.wav");
Clockwork.voices:Add("Vortigaunt", "Pleasure", "With pleasure...", "vo/npc/vortigaunt/pleasure.wav");
Clockwork.voices:Add("Vortigaunt", "Prevail", "We shall prevail.", "vo/npc/vortigaunt/prevail.wav");
Clockwork.voices:Add("Vortigaunt", "Regrettable", "This is regrettable.", "vo/npc/vortigaunt/regrettable.wav");
Clockwork.voices:Add("Vortigaunt", "Stand Clear", "Stand clear!", "vo/npc/vortigaunt/standclear.wav");
Clockwork.voices:Add("Vortigaunt", "Still Here", "We are still here.", "vo/npc/vortigaunt/stillhere.wav");
Clockwork.voices:Add("Vortigaunt", "Survived 1", "We have survived darker times.", "vo/npc/vortigaunt/vques06.wav");
Clockwork.voices:Add("Vortigaunt", "Survived 2", "We have survived worse across the ages.", "vo/npc/vortigaunt/seenworse.wav");
Clockwork.voices:Add("Vortigaunt", "That Is All", "That is all.", "vo/npc/vortigaunt/thatisall.wav");
Clockwork.voices:Add("Vortigaunt", "This Body", "This body is yours to command.", "vo/npc/vortigaunt/bodyyours.wav");
Clockwork.voices:Add("Vortigaunt", "To The Void", "To the void with you!", "vo/npc/vortigaunt/tothevoid.wav");
Clockwork.voices:Add("Vortigaunt", "Trouble No More", "That one shall trouble us no more.", "vo/npc/vortigaunt/troubleus.wav");
Clockwork.voices:Add("Vortigaunt", "Turning Point", "This marks a turning point.", "vo/npc/vortigaunt/vques04.wav");
Clockwork.voices:Add("Vortigaunt", "Unconvinced", "We remain unconvinced.", "vo/npc/vortigaunt/vanswer01.wav");
Clockwork.voices:Add("Vortigaunt", "V1", "Ah'Glaa.", "vo/npc/vortigaunt/vortigese02.wav");
Clockwork.voices:Add("Vortigaunt", "V2", "Tahh.", "vo/npc/vortigaunt/vortigese03.wav");
Clockwork.voices:Add("Vortigaunt", "V3", "Dew'it.", "vo/npc/vortigaunt/vortigese04.wav");
Clockwork.voices:Add("Vortigaunt", "V4", "Langh.", "vo/npc/vortigaunt/vortigese05.wav");
Clockwork.voices:Add("Vortigaunt", "V5", "Gangh.", "vo/npc/vortigaunt/vortigese07.wav");
Clockwork.voices:Add("Vortigaunt", "V6", "Gulanga!", "vo/npc/vortigaunt/vortigese08.wav");
Clockwork.voices:Add("Vortigaunt", "V7", "Gallah'lung.", "vo/npc/vortigaunt/vortigese09.wav");
Clockwork.voices:Add("Vortigaunt", "V8", "Gerr, galling gerr a'la gam.", "vo/npc/vortigaunt/vortigese11.wav");
Clockwork.voices:Add("Vortigaunt", "V9", "Gerr, lung'gung. Jella'gerr.", "vo/npc/vortigaunt/vortigese12.wav");
Clockwork.voices:Add("Vortigaunt", "We Assure", "Likewise, we assure.", "vo/npc/vortigaunt/vanswer15.wav");
Clockwork.voices:Add("Vortigaunt", "We Can Spare", "That is all we can spare.", "vo/npc/vortigaunt/allwecanspare.wav");
Clockwork.voices:Add("Vortigaunt", "We Stay", "Here we stay.", "vo/npc/vortigaunt/herewestay.wav");
Clockwork.voices:Add("Vortigaunt", "We Will Help", "We will help you.", "vo/npc/vortigaunt/wewillhelp.wav");
Clockwork.voices:Add("Vortigaunt", "Where To", "Where to now? And to what end?", "vo/npc/vortigaunt/whereto.wav");
Clockwork.voices:Add("Vortigaunt", "Wish Right", "We wish you are right.", "vo/npc/vortigaunt/vanswer12.wav");
Clockwork.voices:Add("Vortigaunt", "Worthless", "Our life is worthless, unless spent on freedom.", "vo/npc/vortigaunt/worthless.wav");
Clockwork.voices:Add("Vortigaunt", "Yes", "Yessss.", "vo/npc/vortigaunt/yes.wav");
Clockwork.voices:Add("Vortigaunt", "Yes forward", "Yes, forward.", "vo/npc/vortigaunt/yesforward.wav");
